HitChecker=AltHitChecker
CollectionBean=AltCollectionBean
DataBean=AltDataBean
Point=AltPoint
HitCheckerTest=AltHitCheckerTest
hitChecker=altHitChecker
dataBean=altDataBean
collectionBean=altCollectionBean
processRequest=altProcessRequest
isHit=altIsHit